### Register a new user
POST http://localhost:8080/register
Content-Type: application/json

{
    "name": "Test User",
    "password": "password123",
    "email": "test@example.com",
    "isAdmin": false
}

### Login a user
POST http://localhost:8080/login
Content-Type: application/json

{
    "email": "test@example.com",
    "password": "password123"
}

### Access a protected route
### Before sending this request, replace YOUR_TOKEN_HERE with the JWT you received when logging in.
GET http://localhost:8080/protected
Cookie: jwt="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTAsIm5hbWUiOiJUZXN0IFVzZXIiLCJlbWFpbCI6InRlc3RAZXhhbXBsZS5jb20iLCJpYXQiOjE2ODQwMjU0OTAsImV4cCI6MTY4NDExMTg5MH0.8NkgZfaI4ReVLa1KJ8z11MR7prZCcdxYW2X6zx6_HfI"

###

GET http://localhost:8080/me
Cookie: jwt="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTAsIm5hbWUiOiJUZXN0IFVzZXIiLCJlbWFpbCI6InRlc3RAZXhhbXBsZS5jb20iLCJpYXQiOjE2ODQwMjU0OTAsImV4cCI6MTY4NDExMTg5MH0.8NkgZfaI4ReVLa1KJ8z11MR7prZCcdxYW2X6zx6_HfI"