### Register a new user
POST http://localhost:8080/register
Content-Type: application/json

{
    "name": "Test User",
    "password": "password123",
    "email": "test@example.com",
    "isAdmin": false
}

### Login a user
POST http://localhost:8080/login
Content-Type: application/json

{
    "email": "test@example.com",
    "password": "password123"
}

### Access a protected route
### Before sending this request, replace YOUR_TOKEN_HERE with the JWT you received when logging in.
GET http://localhost:8080/protected
Cookie: jwt="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwibmFtZSI6IlRlc3QgVXNlciIsImVtYWlsIjoidGVzdEBleGFtcGxlLmNvbSIsImlhdCI6MTY4Mzg5MDUxNiwiZXhwIjoxNjgzOTc2OTE2fQ.wnV2f_cVRdkNduhjjJRLS5CvRd8UAMlI-oUIqFjUCZw"

###

GET http://localhost:8080/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NiwibmFtZSI6IlRlc3QgVXNlciIsImVtYWlsIjoidGVzdEBleGFtcGxlLmNvbSIsImlhdCI6MTY4Mzg5MzEyNSwiZXhwIjoxNjgzOTc5NTI1fQ.VyR9roAmskYrb6ao-egaeSnHI_x8n0QAqLj15kT-NW0